# Generated by Django 4.1.7 on 2023-02-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('inspector_id', models.AutoField(primary_key=True, serialize=False)),
                ('successful_detentions', models.SmallIntegerField(blank=True, null=True)),
                ('factor_of_utility', models.SmallIntegerField()),
                ('authority', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'inspector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('performer_id', models.AutoField(primary_key=True, serialize=False)),
                ('successful_detentions', models.SmallIntegerField(blank=True, null=True)),
                ('factor_of_utility', models.SmallIntegerField()),
                ('authority', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'performer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskForce',
            fields=[
                ('task_force_id', models.AutoField(primary_key=True, serialize=False)),
                ('success_rate', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'task_force',
                'managed': False,
            },
        ),
    ]
